### ISSUE TITLE
Box Models - size?

### ISSUE THREAD

**Issue by gduarterodrigues** [clbx/LoveCube#1]
Hey, I am not familiar with the ESP-32 or the Display, but I do have an 3d printer available. What dimensions do you think would be good for the box 3d model? Maybe we can share models here?

**Comment by clbx** [comment]
The STL is available in the [repository](https://github.com/clbx/LoveCube/blob/master/LoveCube%20Box.stl) It doesn't look like I uploaded the lid, and I doubt I still have the model. Its honestly a very simple model I put together quickly.
